/* 
 * This message is auto generated by ROS#. Please DO NOT modify.
 * Note:
 * - Comments from the original code will be written in their own line 
 * - Variable sized arrays will be initialized to array of size 0 
 * Please report any issues at 
 * <https://github.com/siemens/ros-sharp> 
 */



namespace RosSharp.RosBridgeClient.MessageTypes.ProcrobFunctional
{
    public class FRClientGoal : Message
    {
        public const string RosMessageName = "procrob_functional/FRClientGoal";

        public byte order_id { get; set; }
        public string order_argument { get; set; }

        public FRClientGoal()
        {
            this.order_id = 0;
            this.order_argument = "";
        }

        public FRClientGoal(byte order_id, string order_argument)
        {
            this.order_id = order_id;
            this.order_argument = order_argument;
        }
    }
}
